# Generated by Django 2.1.7 on 2019-03-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('home_image', models.ImageField(upload_to='media')),
                ('project_title_bg', models.ImageField(upload_to='media')),
                ('client', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('essence', models.CharField(blank=True, max_length=100)),
                ('stories', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_image')),
                ('project_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.project')),
            ],
        ),
    ]
