# Generated by Django 2.1.4 on 2019-03-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190322_0453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hero_section',
            new_name='home_cover',
        ),
    ]
