# Generated by Django 2.1.4 on 2019-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='services',
            field=models.CharField(help_text='ay kalam f ay 7ta ', max_length=500),
        ),
    ]
