# Generated by Django 2.1.4 on 2019-03-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0002_auto_20190321_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='services',
            field=models.CharField(help_text='put %* between each service', max_length=500),
        ),
    ]
