# Generated by Django 2.1.4 on 2019-03-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0003_auto_20190322_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='services',
            field=models.CharField(help_text='put %* between each service', max_length=1000),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
